# @adibenc

services:
  # wip nginx
  py-masonite:
    build: ./src/ms-aml
    container_name: "py-masonite"
    restart: always
    ports:
      - ${DOCKER_APP_PORT}:8000
    # network_mode: host
    volumes:
      - ./tmp:/tmp/local
      # - ./var/log/node/:/app/app/logs/
    command: bash -c "/app/setup.sh"
    healthcheck:
      test: ["CMD", "echo"]
      interval: 5m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    extra_hosts:
      - "l1:172.17.0.1"
      - "host.docker.internal:host-gateway"
  
  # cyper service
  neo4j:
    image: neo4j:4.4.37-community
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      # - $HOME/neo4j/data:/data
      - ./data:/data

  zenml:
    image: zenmldocker/zenml-server
    container_name: zenml
    ports:
      - "8080:8080"
    environment:
      - ZENML_STORE_URL=${ZENML_STORE_URL}
    # links:
    #   - mysql
    # depends_on:
    #   - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # restart: on-failure
    restart: always
  